# Autogenerated by devscripts/update-version.py

__version__ = '2025.11.12.1'

RELEASE_GIT_HEAD = 'd1f7daee0ea537553255d3b26131e147699429d2'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.11.12'
