# Autogenerated by devscripts/update-version.py

__version__ = '2025.07.21.1'

RELEASE_GIT_HEAD = '8424b4ef1828ea9cc987092d91bd63b0fa0d8a00'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.07.21.1'
