# Autogenerated by devscripts/update-version.py

__version__ = '2026.01.31.1'

RELEASE_GIT_HEAD = 'f01d74fefede5834d0f83ed48b77d1b28c885def'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2026.01.31'
